doctrine:
  dbal:
    url: '%env(resolve:DATABASE_URL)%'

    # IMPORTANT: You MUST configure your server version,
    # either here or in the DATABASE_URL env var (see .env file)
    #server_version: '5.7'
  orm:
    auto_generate_proxy_classes: true
    naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
    auto_mapping: true
    mappings:
      Storage:
        type: annotation
        dir: "%kernel.project_dir%/src/Storage/Doctrine/Main/Entity"
        is_bundle: false
        prefix: Storage\Doctrine\Main\Entity
    filters:
      soft_deletable:
        class: Gedmo\SoftDeleteable\Filter\SoftDeleteableFilter
        enabled: true
    quote_strategy: common.orm.quote_strategy
