framework:
  default_locale: hr
  translator:
    default_path: '%kernel.project_dir%/translations'
    paths:
      - "%kernel.project_dir%/src/Common/Infrastructure/Translations"
      - "%kernel.project_dir%/src/UserIdentity/Infrastructure/Translations"
    fallbacks:
      - en
