version: "3"

services:
  backend:
    build:
      context: ./docker/php-fpm
    restart: unless-stopped
    volumes:
      - ./docker/php-fpm/custom.ini:/usr/local/etc/php/conf.d/custom.ini:ro
      - .:/var/www/app
    networks:
      - ddd_education
  nginx:
    image: nginx:1.17.3
    restart: unless-stopped
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./public/:/usr/share/nginx/ddd_education:ro
    networks:
      - ddd_education
    depends_on:
      - backend
    command: [nginx, "-g", "daemon off;"]
  storage:
    image: postgres:9.6.5
    restart: unless-stopped
    networks:
      - ddd_education

networks:
  ddd_education:
    external: false
